### ISSUE TITLE
Download links: List index out of range error.

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#139]
https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0b13/linux-x86_64/en-US/firefox-57.0b13.tar.bz2

```
Traceback (most recent call last):
  File "/home/ubuntu/git-clones/PollBot/pollbot/views/release.py", line 19, in wrapped
    response = await task(product, version)
  File "/home/ubuntu/git-clones/PollBot/pollbot/tasks/bedrock.py", line 114, in download_links
    status = build_version_id(last_release) >= build_version_id(version)
  File "/home/ubuntu/git-clones/PollBot/pollbot/utils.py", line 57, in build_version_id
    major, minor, patch = version_parts(parts)
  File "/home/ubuntu/git-clones/PollBot/pollbot/utils.py", line 23, in version_parts
    minor = parts[1]
IndexError: list index out of range
```

**Comment by Natim** [comment]
This is because the beta version doesn't contain the version number in the URL anymore:

https://download.mozilla.org/?product=firefox-beta-latest-ssl&os=linux64&lang=fr
