### ISSUE TITLE
Retry if a service is unavailable

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#167]
```
0, message='Attempt to decode JSON with unexpected mimetype: '
Traceback (most recent call last):
  File "/home/ubuntu/git-clones/PollBot/pollbot/views/release.py", line 20, in wrapped
    response = await task(product, version)
  File "/home/ubuntu/git-clones/PollBot/pollbot/tasks/telemetry.py", line 80, in update_parquet_uptake
    build_ids = await get_build_ids_for_version(product, version)
  File "/home/ubuntu/git-clones/PollBot/pollbot/tasks/buildhub.py", line 58, in get_build_ids_for_version 
    data = await response.json()
  File "/home/ubuntu/git-clones/PollBot/.venv/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 795, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: '
```

**Comment by Natim** [comment]
I guess the way delievery-dashboard works is sufficient to retry things.
