### ISSUE TITLE
main summary uptake returns an error

### ISSUE THREAD

**Issue by magopian** [mozilla/PollBot#226]
https://pollbot.services.mozilla.com/v1/devedition/63.0b2/telemetry/main-summary-uptake returns

```json
{"status": "error", "message": "string indices must be integers"}
```

**Comment by magopian** [comment]
Filed a bug : https://bugzilla.mozilla.org/show_bug.cgi?id=1489506

**Comment by bqbn** [comment]
I see the following error in the app.

```
Sep 07 18:45:22 ip-172-31-11-84 docker-pollbot[2453]: string indices must be integers
Sep 07 18:45:22 ip-172-31-11-84 docker-pollbot[2453]: Traceback (most recent call last):
Sep 07 18:45:22 ip-172-31-11-84 docker-pollbot[2453]: File "/app/pollbot/views/release.py", line 21, in wrapped
Sep 07 18:45:22 ip-172-31-11-84 docker-pollbot[2453]: response = await task(product, version)
Sep 07 18:45:22 ip-172-31-11-84 docker-pollbot[2453]: File "/app/pollbot/tasks/telemetry.py", line 122, in main_summary_uptake
Sep 07 18:45:22 ip-172-31-11-84 docker-pollbot[2453]: query_info = await get_query_info_from_title(session, query_title)
Sep 07 18:45:22 ip-172-31-11-84 docker-pollbot[2453]: File "/app/pollbot/tasks/telemetry.py", line 74, in get_query_info_from_title
Sep 07 18:45:22 ip-172-31-11-84 docker-pollbot[2453]: body = [query for query in body
Sep 07 18:45:22 ip-172-31-11-84 docker-pollbot[2453]: File "/app/pollbot/tasks/telemetry.py", line 75, in <listcomp>
Sep 07 18:45:22 ip-172-31-11-84 docker-pollbot[2453]: if not query['name'].startswith('Copy of') and
Sep 07 18:45:22 ip-172-31-11-84 docker-pollbot[2453]: TypeError: string indices must be integers
```

**Comment by peterbe** [comment]
It's still busted. But in a different way. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1489506#c20
