### ISSUE TITLE
https://archive.mozilla.org/pub/firefox/nightly/latest-date-l10n/ is broken with latest nightly

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#91]
firefox-date-57.0a1-linux-x86_64-de-20170902072441-20170904182804.partial.mar

**Comment by leplatrem** [comment]
Is this error related? (taken from kinto-ota dev):
```
Traceback (most recent call last):
  File "/home/ubuntu/git-clones/PollBot/pollbot/views/release.py", line 26, in wrapped
    response = await task(product, version)
  File "/home/ubuntu/git-clones/PollBot/pollbot/tasks/bedrock.py", line 114, in download_links
    status = build_version_id(last_release) >= build_version_id(version)
  File "/home/ubuntu/git-clones/PollBot/pollbot/utils.py", line 44, in build_version_id
    major, minor, patch = version_parts(parts)
  File "/home/ubuntu/git-clones/PollBot/pollbot/utils.py", line 21, in version_parts
    minor = parts[1]
IndexError: list index out of range
```

**Comment by Natim** [comment]
I don't think so but we should look at it as well.

**Comment by Natim** [comment]
Fixed with https://github.com/mozilla/PollBot/commit/2ad603d525a8f33fed29ebdc4110d7bfc5da0fa3
